name: 部署项目到服务器

on:
  push:
    branches: [ master ] # 指定触发分支，当代码推送到 main 分支时触发工作流

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 工作流在最新的Ubuntu系统环境中运行

    steps:
      - name: 拉取项目代码
        uses: actions/checkout@v3

      - name: 设置Node.js环境
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 安装项目依赖并构建
        run: |
          npm install
          npm run build
        
      - name: 添加服务器主机密钥到known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: 部署到服务器
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          sync: true
          source: ./dist/
          target: /var/www/MyWebsite